version: "3.8"

services:
  mongodb-server-1:
    image: mongo:latest # mongodb/mongodb-community-server:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
#    environment:
#      MONGODB_INITDB_ROOT_USERNAME: root
#      MONGODB_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - service-network

  mongodb-server-2:
    image: mongo:latest # mongodb/mongodb-community-server:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27018:27017
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    environment:
#      MONGODB_INITDB_ROOT_USERNAME: root
#      MONGODB_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    networks:
      - service-network

  mongodb-server-3:
    image: mongo:latest # mongodb/mongodb-community-server:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27019:27017
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    environment:
#      MONGODB_INITDB_ROOT_USERNAME: root
#      MONGODB_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    networks:
      - service-network

  mongodb-express:
    container_name: mongodb-express
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-server-1 # this line will work as expected only if ME_CONFIG_MONGODB_URL is set simultaneounly, currently. (https://github.com/mongo-express/mongo-express-docker/issues/113)
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://mongodb-server-1:27017
    depends_on:
      - mongodb-server-1
    networks:
      - service-network

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  service-network:
