services:
  mongodb-server:
    container_name: mongodb-server
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root

  mongodb-express:
    container_name: mongodb-express
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-server # this line will work as expected only if ME_CONFIG_MONGODB_URL is set simultaneounly, currently. (https://github.com/mongo-express/mongo-express-docker/issues/113)
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://mongodb-server:27017
    depends_on:
      - mongodb-server

volumes:
  mongodb-data:
    name: mongodb-data
