version: '3'
services:
  app:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
volumes:
  mysql-data:
    name: mysql-data