version: '3'

services:
  app:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laravel

volumes:
  postgres-data:
    name: postgres-data
    