version: '3'
services:
  pgserver:
    container_name: postgres-server
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  pgadmin:
    container_name: pgadmin
    # image: dpage/pgadmin4:latest
    image: dpage/pgadmin4:9.0.0
    depends_on:
      pgserver:
        condition: service_healthy
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_SERVER_JSON_FILE: '/config/default_connection.json'
    volumes:
      - ./pgadmin:/config
    ports: 
      - "5050:80"
    restart: always
      
volumes:
  postgres-data:
    name: postgres-data
