version: '3'

services:
  app:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    name: redis-data